### ISSUE TITLE
Printful API - 2 keys?

### ISSUE THREAD

**Issue by christopherdowson** [atcipher-group/craft-printful-api#4]
Hi, can I just ask - I'm only given 1 API key from printful through the developer portal, but the plugin settings requires 2. Am I missing something?

**Comment by atcipher-group** [comment]
Hi @christopherdowson,

It's a bit of an odd setup but you need to create two accounts for two different API Keys. The first would be "A single store" API Key that directly links to your Printful store. The other needs to be an "Account (all stores)" API Key.

The "single store" API Key would be entered into the API Key text box in the plugin. The All Access API Key from the plugin will contain the "Account (all stores)" API Key.

In the next release, we will be looking to update the documentation as well as a few features. I will ensure that we update the documentation to clarify this issue in the future.

Many thanks for choosing to use our Craft Plugin and if you need any other help, please let us know as soon as possible.

**Comment by christopherdowson** [comment]
Ahhhhh, yeah - that makes sense! Thank you - should hopefully be plain sailing from here :)
